version: "3"
services:
      jenkins:
        image: pyjenkins
        container_name: "jenkins_agendador"
        ports:
            - "8000:8080"
            - "50000:50000"
        volumes:
            - "./jenkins_home:/var/jenkins_home"
            - "./python_scripts:/python_scripts"
# 408ac5bd232f4d8fb04c86d0885ec12f